spring:
  data:
    mongodb:
      uri: ${MONGO_URI} # Make sure to add replicaSet to the MongoDB URI
  graphql:
    path:
cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    end-point:
      uri: ${AWS_ENDPOINT}
message:
  concurrency: 10
  queue:
    ApplyTransactionCmd: ApplyTransactionQueue
    CancelTransactionCmd: CancelTransactionQueue
    ExecutionCompletedEvt: ExecutionCompletedQueue
    ExecutionStartedEvt: ExecutionStartedQueue