logging:
  level:
    io.github.olegshishkin: trace
    org.springframework.data.mongodb: debug
    org.springframework.r2dbc: debug
    io.r2dbc.postgresql.QUERY: debug
    io.r2dbc.postgresql.PARAM: debug
spring:
  graphql:
    path: /graphql
  r2dbc:
    pool:
      initial-size: 5
      max-size: 5