spring:
  r2dbc:
    url: ${DB_URL}
    pool:
      max-idle-time: 1m
      validation-query: select 1
    username: ${DB_USERNAME}
    password: ${DB_PASSWD}
  graphql:
    path:
cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    end-point:
      uri: ${AWS_ENDPOINT}
message:
  concurrency: 10
  queue:
    ApplyTransactionCmd: ApplyTransactionQueue
    CancelTransactionCmd: CancelTransactionQueue
    ExecutionCompletedEvt: ExecutionCompletedQueue
    ExecutionStartedEvt: ExecutionStartedQueue